<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RWC-MLCCS.WindowsIntegration</AssemblyName>
    <RootNamespace>RWC_MLCCS.WindowsIntegration</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RWC-MLCCS.Common\RWC-MLCCS.Common.csproj" />
  </ItemGroup>

</Project>
