<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RWC-MLCCS.Common\RWC-MLCCS.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RWC-MLCCS.Server</AssemblyName>
    <RootNamespace>RWC_MLCCS.Server</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>..\..\assets\MLCCS.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
